### ISSUE TITLE
Issue with environment variables

### ISSUE THREAD

**Issue by samedney** [lxdock/lxdock#107]
Using Ubuntu 16.04. 

Im already using lxdock successfully, and now Im trying to start using some environment variables to speed things up. 

It seems as though the environment variables are not picked up by the lxdock file. What am I doing wrong?

I have this `.env` file in the same directory as my `.lxdock.yml` file:

```
ICFM=electric
ICFM_APP=electric.icfm
ICFM_DB=electric.db
```

And this is the `.lxdock.yml` file.

```
name: ${ICFM}
image: ubuntu/xenial

containers:

  - name: app
    hostnames: 
      - ${ICFM_APP}

  - name: db
    hostnames:
      - ${ICFM_DB}

provisioning:
  - type: ansible
    playbook: /home/sam-e/containers/playbooks/icfm/playbook.yml
    groups:
      app-servers:
        - app
      db-servers:
        - db
```

I also tried doing the vars using `export ICFM=electric` and I still get the same problem.

I also tried encapsulating the variables in quotes (both single and double).

I get these errors (seemingly a random selection of the two):

```
The LXDock file is invalid because: expected a valid identifer no longer than 63 characters, starting with letters and made up of letters, digits and dashes @ name
```
or
```
The LXDock file is invalid because: expected a valid hostname @ containers.0.hostnames.0
```

Any ideas?
