### ISSUE TITLE
Example lxdock.yml fails on required key not provided

### ISSUE THREAD

**Issue by geoffmcnamara** [lxdock/lxdock#42]
I attempted a simple lxdock.yml file with this content:

```
name: myproject

containers:
  - name: node1
  - image: ubuntu/xenial

  - name: node2
  - image: ubuntu/xenial
```

But running "lxdock up" results in this fatal error:
"The LXDock file is invalid because: required key not provided @ containers.1.name"

Can't find anything in the docs or online - what did I miss.
Thanks
-geoff-

**Comment by ellmetha** [comment]
The following YML works for me:

```
name: myproject

containers:
  - name: node1
    image: ubuntu/xenial
  - name: node2
    image: ubuntu/xenial
```
